### ISSUE TITLE
Ajouter un moteur de recherche

### ISSUE THREAD

**Issue by thomasarmel** [haysberg/azurwiki#73]
Mettre un moteur de recherche pour retrouver ses pages plus facilement

**Comment by PierreKy-org** [comment]
Comment tu intègres un moteur de recherche dans docusaurus pour le coup ?
Une feature qui doit être activée ?

**Comment by thomasarmel** [comment]
J'ai trouvé https://docusaurus.io/fr/docs/search , j'espère que ça peut être ajouté facilement chez nous

**Comment by haysberg** [comment]
Alors j'ai eu quelques soucis il y a quelques jours pour l'intégrer.
En fait le souci c'est que pour la plupart des moteurs supportés, en fait il faut passer par une API externe, et ça je suis pas trop pour.

Pour les moteurs qui font de la recherche en local pourquoi pas, par contre en terme de dépendances ça pourrait bloquer. On va passer sur docusaurus V3 quand ça va sortir, et ça va déjà être un peu la merde pour faire la transition.

**Comment by thomasarmel** [comment]
Autrement, tant qu'on a pas trop de pages on peut aussi utiliser un moteur de recherche qui tourne côté client: http://elasticlunr.com/
