### ISSUE TITLE
Add linting and formating to project

### ISSUE THREAD

**Issue by Apoorva64** [haysberg/azurwiki#89]
Adding formatting to the project

- [ ] Choose formatter

**Comment by haysberg** [comment]
Hello,

Honestly that sounds very complicated for a project where most participants will only have to add and edit Markdown files.
Even though the project is indeed running with JavaScript, we do not write JavaScript ourselves, and I actually don't expect contributors to install npm and run the website themselves if they don't want to.

#91 is much more likely to give us real value, but we don't need a linter right now, especially given the size of the project, sorry.

Maybe we could add a Markdown linter with [pre-commit](https://www.npmjs.com/package/pre-commit) but it might be a bit of a pain when we consider ease of use for contributors so we'll have to think about it.
